arch_root: /mnt

hostname: bon
timezone: Europe/Berlin
country: Germany
locales:
  - en_US
  - de_DE

user:
  name: croissong
  group: croissong
  uid: 1000
  comment: Jan MÃ¶ller
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: jan.moeller0@gmail.com

extra_packages:
  - git
  - ripgrep
  - zsh

extra_aur_packages:
  - gscreenshot
  - emacs-git

dotfiles:
  repo: "https://github.com/zoresvit/dotfiles"
  install_cmd: "stow -d ${HOME}/dotfiles -S albert bash chromium conky flameshot git goldendict mime termite tmux vim xmonad xorg"
  deps:
    - stow
    - xclip
    
# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:
    - name: arch
      start: 512MiB
      end: 100%
      filesystem: btrfs
      mountpoint: /
      encrypt: false
      opts: noatime,subvol=@
    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot
      encrypt: false

btrfs__subvolumes:
  "{{ arch_root }}/@":
     state: present
  "{{ arch_root }}/@tmp":
     state: present
  "{{ arch_root }}/@var":
     state: present
  "{{ arch_root }}/@home":
     state: present

packages:
  - arch-wiki-lite
  - coreutils
  - dialog
  - glances
  - linux-firmware
  - lsof
  - moreutils
  - rsync
  - sysstat
  - wpa_supplicant
  - pciutils
  