arch_root: /mnt

ansible_become_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31656533313762323636393839623433613464653134643532313133656332613730376139663165
  3935376439376336393462326338313764643266666365300a613833643538306635636435623063
  62316262316536663138366166393766383664653434313161616439313765333230383435326165
  3063636134626364660a393038336362383962343436353761346534333237336133363336643661
  3137

hostname: bon
timezone: Europe/Berlin
country: Germany
locales:
  - en_US
  - de_DE

user:
  name: &username croissong
  group: *username
  uid: 1000
  comment: Jan MÃ¶ller
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: jan.moeller0@gmail.com

repos:
  emacs: 'git@github.com:Croissong/.emacs.d.git'
  dotfiles: 'git@github.com:Croissong/dotfiles.git'
  pass: 'git@gitlab.com:Croissong/password-store.git'
  passOtp: 'git@gitlab.com:Croissong/pass-otp.git'
        
# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:
    - name: arch
      start: 512MiB
      end: 100%
      filesystem: btrfs
      mountpoint: /
      encrypt: false
      opts: noatime,subvol=@
    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot
      encrypt: false

btrfs__subvolumes:
  "{{ arch_root }}/@":
     state: present
  "{{ arch_root }}/@tmp":
     state: present
  "{{ arch_root }}/@var":
     state: present
  "{{ arch_root }}/@home":
     state: present
